#######################################################################################
# Book settings
title: "Rogue Docs"
logo: img/2.svg
author: NeneWang
email: nelson.wang80@bcmail.cuny.edu
description: >- # this means to ignore newlines until "baseurl:"
  This are my notes and documentation for research.


only_build_toc_files: true

# Bibliography settings
bibtex_bibfiles:
  - references.bib

execute:
  execute_notebooks: cache
  stderr_output: "remove"
  allow_errors: true
  timeout: 120

html:
  # FIXME: surely we could allow internal or relative links somehow?
  # (The documentation says only that HTML is allowed, nothing about the base URL is mentioned.)
  # Then we could link to the changelog in the *same* build of the docs.
  # announcement: '⚠️The 0.13 release refactored our HTML, so double-check your custom CSS rules!⚠️'
  favicon: img/favicon.png
  # google_analytics_id: UA-52617120-7
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://nenewang.github.io/
  # analytics:
  #   google_analytics_id = ''

repository:
  url: https://github.com/NeneWang/nenewang.github.io
  branch: main
  path_to_book: /

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

parse:
  myst_substitutions:
      sub3: My _global_ value!
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

sphinx:
  recursive_update: true
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite
    # unknown_mime_type - application/vnd.plotly.v1+json and application/vnd.bokehjs_load.v0+json
    # domains - sphinx_proof.domain::prf needs to have `resolve_any_xref` method
    # mime_priority - latex priority not set in myst_nb for text/html, application/javascript
    suppress_warnings: ["mystnb.unknown_mime_type", "myst.domains", "mystnb.mime_priority", "myst.xref_missing", "myst.header"]
    copybutton_prompt_text: "$"
    nb_execution_show_tb: True
    nb_execution_timeout: 120
    html_extra_path:
      - img/badge.svg
    intersphinx_mapping:
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null
      sd:
        - https://sphinx-design.readthedocs.io/en/latest
        - null
    language: en
    latex_elements:
        preamble: |
          \newcommand\N{\mathbb{N}}
          \newcommand\floor[1]{\lfloor#1\rfloor}
          \newcommand{\bmat}{\left[\begin{array}}
          \newcommand{\emat}{\end{array}\right]}
    # TODO: #917 this path will be the default in sphinx v4
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # However, it is incompatible with the mathjax config below for macros
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    rediraffe_branch: 'master'
    sd_fontawesome_latex: True

    html_theme_options:
      navigation_with_keys: false

  extra_extensions:
    - sphinx_click.ext
    - sphinx_inline_tabs
    - sphinxext.rediraffe
    - sphinx_proof
    - sphinx_examples
